### ISSUE TITLE
Wrong SDDL identifier

### ISSUE THREAD

**Issue by synopse** [huner2/go-sddlparse#2]
https://github.com/huner2/go-sddlparse/blob/55f49cc5e73201cc9831072363bb819c4b3c68b3/constants.go#L388
Shouldn't the constant here be CY and not CD?
See https://learn.microsoft.com/en-us/windows/win32/secauthz/sid-strings
`"CY" 	SDDL_CRYPTO_OPERATORS 	Crypto operators. The corresponding RID is DOMAIN_ALIAS_RID_CRYPTO_OPERATORS = S-1-5-32-569`

CD is already used for SDDL_CERTSVC_DCOM_ACCESS:
`"CD" 	SDDL_CERTSVC_DCOM_ACCESS 	Users who can connect to certification authorities using Distributed Component Object Model (DCOM). The corresponding RID is DOMAIN_ALIAS_RID_CERTSVC_DCOM_ACCESS_GROUP. `

**Comment by huner2** [comment]
Fixed in v1.0.3
